// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// read_sl2_cpp
DataFrame read_sl2_cpp(std::string path);
RcppExport SEXP _sonaR_read_sl2_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_sl2_cpp(path));
    return rcpp_result_gen;
END_RCPP
}
// read_sl3_cpp
DataFrame read_sl3_cpp(std::string path);
RcppExport SEXP _sonaR_read_sl3_cpp(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(read_sl3_cpp(path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sonaR_read_sl2_cpp", (DL_FUNC) &_sonaR_read_sl2_cpp, 1},
    {"_sonaR_read_sl3_cpp", (DL_FUNC) &_sonaR_read_sl3_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_sonaR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
