# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A "No Frills" Faster Version in C++
#'
#' No error checking (not even for file existence). No fancy names for channel/etc.
#' No unnesting of validity fields. BUT, it's wicked fast.
#'
#' @md
#' @param path
#' @return data frame (tibble)
#' @export
#' @examples
#' read_sl2_cpp(system.file("exdat", "example.sl2", package="arabia")))
read_sl2_cpp <- function(path) {
    .Call(`_sonaR_read_sl2_cpp`, path)
}

#' Function to read .sl3 files
#' @md
#' @param path
#' @return data frame (tibble)
#' @export
#' @examples
#' #read_sl3_cpp(system.file("exdat", "example.sl2", package="arabia")))
read_sl3_cpp <- function(path) {
    .Call(`_sonaR_read_sl3_cpp`, path)
}

