# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' @md
#' @param path to '.sl2' file
#' @return data.frame
#' @export
read_sl2_cpp <- function(path) {
    .Call(`_sonaR_read_sl2_cpp`, path)
}

#'
#' @md
#' @param path to '.sl3' file
#' @return data.frame
#' @export
read_sl3_cpp <- function(path) {
    .Call(`_sonaR_read_sl3_cpp`, path)
}

