# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_slx <- function(path, filesize, display_progress = TRUE) {
    .Call('_sonaR_read_slx', PACKAGE = 'sonaR', path, filesize, display_progress)
}

